Q1 = "select count(name) from movie where ( name like 'Ha%' and rank > 2 and year ==2002) ;"
Q2 = "select max(rank) from movie where (name like 'autom%' and (year == 1983 or year == 1994));"
Q3 = "select count(id) from actor where(gender == 'M' and (fname like '%ei' or lname like 'ei%'));"
Q4 = "select avg(rank) as average_rank_of_movies from movie where((year == 1993 or year==1995 or year==2000) and (rank >= 4.2));"
Q5 = "select sum(rank) from movie where ((name like  '%Hary%') and (year BETWEEN 1981 and 1984) and (rank < 9));"
Q6 = "select min(year) from movie where rank == 5;"
Q7 = "select count(id) from actor where (gender == 'F' or fname == lname); "
Q8 = "select distinct fname from actor where lname like '%ei' ORDER BY fname asc limit 100;"
Q9 = "select id,name as movie_title ,year from movie where year IN (2001,2002,2005,2006) limit 25 offset 10;"
Q10 = "SELECT DISTINCT(lname) FROM Director WHERE fname IN('Yeud','Wolf','Vicky') ORDER BY lname ASC LIMIT 5;"