Q1 = "SELECT * FROM MOVIE order by rank desc limit 10;"
Q2 ="SELECT * FROM MOVIE order by rank desc limit 10 offset 10;"
Q3 = "SELECT name from movie where year > 2004 ;"
Q4 = "SELECT name from movie where rank < 1.1 ;"
Q5 = "SELECT * from movie where year IN (2004,2005,2006);"
Q6 = "SELECT name,year from movie where name like 'Harry%';"
Q7 = "SELECT * from actor where fname like 'christin' and lname not like 'Watson';"
Q8 = "SELECT * from actor where fname like 'woody' and lname like 'Watson';"
Q9 = "SELECT name from movie where year == 1990 and rank == 5;"
Q10 = "SELECT * from actor where fname like 'christin' and lname like 'Watson';"
Q11 = "SELECT name from movie where year between 2003 and 2005;"
Q12 = "SELECT distinct year from movie order by year asc;"
Q13 = "SELECT * from actor where (fname like 'christin' or lname like 'watson') and (gender == 'M') order by fname asc limit 10;"